/*
 * ErrorCodeParse.h
 *
 *  Created on: 2015-10-21
 *      Author: Administrator
 */


#ifndef ERRORCODEPARSE_H_
#define ERRORCODEPARSE_H_

#include "Interface/IDevice.h"

typedef struct __ERRORCODEPARSE
{
	char		errorcode[11];
	char		errordescrible[256];
	DeviceErrorCode		IDCResult;
	DeviceStatus			IDCSta;
}ERRORCODEPARSE, * LPERRORCODEPARSE;

// errorcode					errordescrible
// IDCResult					IDCDev
ERRORCODEPARSE m_ErrorCodeParse[]=
{
	{ "0000000000", "Execute Success", DEVICE_ERROR_SUCCESS, DEVICE_STATUS_ONLINE},
	{ "0000000001",	"Load dynamic library error", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_END},
	{ "0000000002",	"Load lib function error", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_END},
	{ "0000000003",	"Device Type not support", DEVICE_ERROR_NOT_EXISTED, DEVICE_STATUS_END},
	{ "0000000004",	"Open  Device Fail--Not find", DEVICE_ERROR_NOT_EXISTED, DEVICE_STATUS_END},
	{ "0000000005",	"Open  Device Fail--Communication fail", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_HWERROR},
	{ "0000000006",	"Close  Device Fail", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_HWERROR},
	{ "0000000007",	"Execute Fail--Communication fail", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_HWERROR},
	{ "0000000008",	"Parameters not set", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_END},
	{ "0000000009",	"Already close device", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_END},
	{ "0000000010",	"Device has not media", DEVICE_CARDREADER_INVALID_MEDIA, DEVICE_STATUS_ONLINE},
	{ "0000000011",	"Device already has media", DEVICE_CARDREADER_MEDIA_PRESENT, DEVICE_STATUS_ONLINE},
	{ "0000000012",	"Device has media--not inserted in place", DEVICE_CARDREADER_MEDIA_PRESENT, DEVICE_STATUS_ONLINE},
	{ "0000000013",	"Execute command not support", DEVICE_ERROR_OP_NOT_SUPPORTED, DEVICE_STATUS_ONLINE},
	{ "0000000014",	"Execute command timeout", DEVICE_ERROR_TIMEOUT, DEVICE_STATUS_ONLINE},
	{ "1100000000",	"Command word error", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000001",	"Command parameters error", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000002",	"Command can not be executed", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000003",	"Command can not be supported ", DEVICE_ERROR_OP_NOT_SUPPORTED, DEVICE_STATUS_ONLINE},
	{ "1100000004",	"Command data error", DEVICE_ERROR_INTERNAL_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000011",	"Lock card operation fail", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000015",	"EEPROM error", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000020",	"Read megnet error--odd even check error", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000021",	"Read megnet error", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000030",	"Device power off", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_END},
	{ "1100000041",	"IC card operation fail", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000060",	"IC card power cutting-out", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000061",	"IC card active fail", DEVICE_ERROR_HARDWARE_ERROR, DEVICE_STATUS_ONLINE},
	{ "1100000062",	"IC card not support command", DEVICE_ERROR_OP_NOT_SUPPORTED, DEVICE_STATUS_ONLINE},
	{ "1100000063",	"IC card does not respond", DEVICE_ERROR_SUCCESS, DEVICE_STATUS_ONLINE},
	{ "1100000064",	"IC card does not respond", DEVICE_ERROR_SUCCESS, DEVICE_STATUS_ONLINE},
	{ "1100000065",	"IC card does not active", DEVICE_ERROR_SUCCESS, DEVICE_STATUS_ONLINE},
	{ "1100000066",	"Device does not support the type of IC card", DEVICE_CARDREADER_INVALID_MEDIA, DEVICE_STATUS_ONLINE},
	{ "1100000069",	"Device does not support EMV mode", DEVICE_ERROR_SUCCESS, DEVICE_STATUS_ONLINE},
};



#endif /* ERRORCODEPARSE_H_ */
